### ISSUE TITLE
Error encountered with lazy loading disabled while unbanning user.

### ISSUE THREAD

**Issue by Ojsholly** [qirolab/laravel-bannable#13]
Hello. Thanks for your wonderful package. However, I did encounter an error while trying to unban a user account with lazy loading disabled in a non-production environment. Kindly look into this. Thanks.

Attempted to lazy load [bannable] on model [Qirolab\Laravel\Bannable\Models\Ban] but lazy loading is disabled. {"userId":6,"exception":"[object] (Illuminate\\Database\\LazyLoadingViolationException(code: 0): Attempted to lazy load [bannable] on model [Qirolab\\Laravel\\Bannable\\Models\\Ban]

**Comment by hkp22** [comment]
It is not a package issue. To fix this, you should eager load the modal relationship data.
